// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/wiscourhand/httpsvr/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	r.POST("/:svrName/:methodName", handler.RpcMethod)
	r.POST("/idl-info/add/:idlName", handler.AddIdlInfo)
	// your code ...
}
